#! /usr/bin/env python3
from PIL import Image, ImageFont, ImageDraw

def decode_image(file_location="/home/oneal/桌面/ad/flag1.jpg"):
    encoded_image = Image.open(file_location)
    red_channel = encoded_image.split()[0]
 
    x_size = encoded_image.size[0]
    y_size = encoded_image.size[1]
 
    decoded_image = Image.new("RGB", encoded_image.size)
    pixels = decoded_image.load()
    sum=0
    for i in range(x_size):
        for j in range(y_size):      
            if bin(red_channel.getpixel((i, j)))[-1] == '0':
                sum+=0;
            else:
                sum+=1;
    #decoded_image.save("/home/oneal/桌面/ad/decoded_image.png")
    print(sum) 
decode_image("/home/oneal/桌面/ad/flag1.jpg")
decode_image("/home/oneal/桌面/ad/flag2.jpg")
decode_image("/home/oneal/桌面/ad/flag3.jpg")
